{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "helper.fullname" .) .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- if or .Values.serviceAccount.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "helper.annotations" (dict "annotations" .Values.commonAnnotations "context" $) | trim | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccount.annotations }}
    {{- include "helper.annotations" (dict "annotations" .Values.serviceAccount.annotations "context" $) | trim | nindent 4 }}
    {{- end }}
  {{- end }}
  labels: {{- include "helper.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.labels }}
    {{- include "helper.tplValue" (dict "value" .Values.serviceAccount.labels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "helper.tplValue" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
{{- end -}}
