{{- if eq .Values.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "helper.annotations" (dict "annotations" .Values.commonAnnotations "context" $) | trim | nindent 4 }}
  {{- end }}
  labels: {{- include "helper.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "helper.tplValue" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels: {{- include "helper.matchLabels" . | nindent 6 }}
  {{- if not .Values.autoscaling.create }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations: {{- include "helper.annotations" (dict "annotations" .Values.podAnnotations "context" $) | trim | nindent 8 }}
      {{- end }}
      labels: {{- include "helper.labels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- include "helper.tplValue" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
{{- include "helper.imagePullSecrets" . | indent 6 }}
      {{- if .Values.extraInitContainers }}
      initContainers: {{- toYaml .Values.extraInitContainers | nindent 8 }}
      {{- end }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "helper.tplValue" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "helper.tplValue" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "helper.tplValue" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "helper.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ template "helper.name" . }}
          image: {{ template "helper.image" . }}
          imagePullPolicy: "{{ include "helper.imagePullPolicy" . }}"
          {{- if .Values.lifecycle }}
          lifecycle: {{- toYaml .Values.lifecycle | nindent 12 }}
          {{- end }}
          {{- if .Values.image.command }}
          command: {{ .Values.image.command }}
          {{- end }}
          {{- if .Values.extraArgs }}
          args:
          {{- range $key, $value := .Values.extraArgs }}
            {{- if $value }}
            - --{{ $key }}={{ $value }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
          {{- end }}
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.extraEnvs }}
            {{- toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
          {{- if or .Values.configMap.loadAsEnvVars .Values.secret.loadAsEnvVars }}
          envFrom:
          {{- if .Values.configMap.loadAsEnvVars }}
            - configMapRef:
                name: {{ default (include "helper.fullname" .) .Values.configMap.name }}
                optional: true
          {{- end }}
          {{- if .Values.secret.loadAsEnvVars }}
            - secretRef:
                name: {{ default (include "helper.fullname" .) .Values.secret.name }}
                optional: true
          {{- end }}
          {{- end }}
          volumeMounts:
          {{- if .Values.configMap.mount.enabled }}
            - name: {{ default (include "helper.fullname" .) .Values.configMap.mount.name  }}
              mountPath: {{ .Values.configMap.mount.path }}
          {{- end }}
          {{- if .Values.secret.mount.enabled }}
            - name: {{ default (include "helper.fullname" .) .Values.secret.mount.name  }}
              mountPath: {{ .Values.secret.mount.path }}
              readOnly: true
          {{- end }}
          {{- if .Values.persistence.create }}
            - name: {{ include "helper.fullname" . }}-{{ .Values.persistence.name }}
              mountPath: {{ .Values.persistence.path }}
          {{- end }}
          {{- if .Values.persistence.existingClaim }}
            - name: {{ .Values.persistence.existingClaim }}
              mountPath: {{ .Values.persistence.path }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.containerPorts }}
          ports: {{- toYaml .Values.containerPorts | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.securityContext }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
        {{- if .Values.extraContainers }}
        {{- toYaml .Values.extraContainers | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.configMap.mount.enabled }}
        - name: {{ .Values.configMap.mount.name }}
          configMap:
            name: {{ default (include "helper.fullname" .) .Values.configMap.name }}
        {{- end }}
        {{- if .Values.secret.mount.enabled }}
        - name: {{ .Values.secret.mount.name }}
          secret:
            secretName: {{ default (include "helper.fullname" .) .Values.secret.name }}
        {{- end }}
        {{- if .Values.persistence.create }}
        - name: {{ include "helper.fullname" . }}-{{ .Values.persistence.name }}
          emptyDir: {{- toYaml .Values.persistence.emptyDir | nindent 12 }}
        {{- else if .Values.persistence.existingClaim }}
        - name: {{ include "helper.fullname" . }}-{{ .Values.persistence.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
{{- end }}
