{{- if and .Values.kind "Deployment" .Values.autoscaling.create }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ default (include "helper.fullname" .) .Values.autoscaling.name }}
  namespace: {{ .Release.Namespace }}
  {{- if or .Values.autoscaling.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "helper.annotations" (dict "annotations" .Values.commonAnnotations "context" $) | trim | nindent 4 }}
    {{- end }}
    {{- if .Values.autoscaling.annotations }}
    {{- include "helper.annotations" (dict "annotations" .Values.autoscaling.annotations "context" $) | trim | nindent 4 }}
    {{- end }}
  {{- end }}
  labels: {{- include "helper.labels" . | nindent 4 }}
    {{- if .Values.autoscaling.labels }}
    {{- include "helper.tplValue" (dict "value" .Values.autoscaling.labels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "helper.tplValue" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "helper.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics: {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
{{- end }}
