{{- if and .Values.metrics.create .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ default (include "helper.fullname" .) .Values.metrics.serviceMonitor.name }}
  namespace: {{ .Release.Namespace }}
  {{- if or .Values.configMap.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "helper.annotations" (dict "annotations" .Values.commonAnnotations "context" $) | trim | nindent 4 }}
    {{- end }}
    {{- if .Values.metrics.serviceMonitor.annotations }}
    {{- include "helper.annotations" (dict "annotations" .Values.metrics.serviceMonitor.annotations "context" $) | trim | nindent 4 }}
    {{- end }}
  {{- end }}
  labels: {{- include "helper.labels" . | nindent 4 }}
    {{- if .Values.metrics.serviceMonitor.labels }}
    {{- include "helper.tplValue" (dict "value" .Values.metrics.serviceMonitor.labels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "helper.tplValue" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  {{- include "helper.tplValue" (dict "value" .Values.metrics.serviceMonitor.endpoints "context" $) | nindent 4 }}
  selector:
    matchLabels: {{- include "helper.matchLabels" . | nindent 6 }}
{{- end }}