name: Lint Charts

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run chart-testing
        id: lint
        uses: HexF/chart-testing-action@v3.0.1
        with:
          command: lint
